### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by GabrielCano89** [FacundoUndiano1/MercadoLiebre#2]
En tamaño del banner cambia en las diferentes vistas. Saludos =)

**Comment by FacundoUndiano1** [comment]
> En tamaño del banner cambia en las diferentes vistas. Saludos =)



> En tamaño del banner cambia en las diferentes vistas. Saludos =)

Modificado!

**Comment by FacundoUndiano1** [comment]
Modificado!
